version: '3.8'
services:
  db:
    container_name: postgresql_db
    image: 5565917/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  app:
    container_name: app
    image: 5565917/app
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.ApiServer:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    restart: always
  pgadmin:
    container_name: pgadmin
    image: 5565917/pgadmin4
   #image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db