"""Added required tables

Revision ID: 32cac2730f12
Revises: 
Create Date: 2021-09-12 00:58:05.381879

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '32cac2730f12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
                    sa.Column('heading', sa.String(), nullable=False),
                    sa.Column('subtitle', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('image', sa.String(), nullable=True),
                    sa.Column('subid', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('heading'),
                    sa.UniqueConstraint('subid')
                    )
    op.create_table('document',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('lincid', sa.String(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('path', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('lincid'),
                    sa.UniqueConstraint('name')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    op.drop_table('category')
    # ### end Alembic commands ###
